### PR TITLE
Feature branch

### PR DESCRIPTION
**Pull request by torobucci**
### Feature branch modificatons

- Added form section in index.html file
- Added styles to the form section in style.css
- Added form section footer images to the images folder

### CODE REVIEW

**Review by frank1738 — CHANGES_REQUESTED** [review]
Hi @torobucci , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!



## Highlights

✅ Correct use of Github workflow
✅ No linter error



## Required Changes ♻️

- [ ] Kindly include the correct instructions to install and run the project locally as this is not a ruby project

## Optional suggestions
N/A
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by torobucci** [comment]
@frank1738 Hello. I haven't understood the change required. I don't know the correct way to install and run the project locally

**Comment by frank1738** [comment]
> @frank1738 Hello. I haven't understood the change required. I don't know the correct way to install and run the project locally



- [ ] You included steps on how to run a ruby on rails project yet this project does not include ruby on rails

image

**Review by iambenkis — APPROVED** [review]
Hi @torobucci , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
Linters are passing 👍 
The project is running successfully 👍 
PR is well descriptive 👍 
## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me **@iambenkis** in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
